version: "3.8"
services:
  server:
    container_name: nechat-server
    build: ./Server
    # ports:
    #   - "25566:25566"
    depends_on:
      - database
  
  database:
    container_name: nechat-database
    build: ./Database
    # ports:
    #   - "3306:3306"

  client:
    container_name: nechat-client
    build: ./Client
    ports:
      - "8080:8080"
    depends_on:
      - server
