version: "3.8"
services:
  server:
    container_name: nechat-server
    build: ./Server
    ports:
      - "25566:25566"
    depends_on:
      - database
    networks:
      - backend
  
  database:
    container_name: nechat-database
    build: ./Database
    ports:
      - "3306:3306"
    networks:
      - backend

  client:
    container_name: nechat-client
    build: ./Client
    ports:
      - "8081:8081"

networks:
  backend: